---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mizar-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      job: mizar-daemon
  template:
    metadata:
      labels:
        job: mizar-daemon
    spec:
      serviceAccountName: mizar-operator
      hostNetwork: true
      hostPID: true
      volumes:
        - name: mizar
          hostPath:
            path: /home
            type: Directory
      containers:
      - image: selgohari/dropletd:latest
        name: mizar-daemon
        securityContext:
            privileged: true
        volumeMounts:
          - name: mizar
            mountPath: /mizar
